version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kenan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
